### ISSUE TITLE
an error occurs

### ISSUE THREAD

**Issue by zha0gongz1** [RedSiege/EyeWitness#569]
#test on Windows7

C:\Users\whoami\Desktop\Tools>EyeWitness.exe --help

Unhandled Exception: System.MissingMethodException: Method not found: 'System.Th
reading.Tasks.Task System.Threading.Tasks.Task.Run(System.Func`1<System.Threadin
g.Tasks.Task>)'.
   at EyeWitness.Program.Main(String[] args)

**Comment by Relkci** [comment]
Since Windows 7 has been unsupported since January 2020, we're going to close this one.   I also believe this may have been the result of not having .net framework / core installed as a dependency on the OS since it wouldn't have originally supported task threading without adding .Net core or 4.0 manually anyway.  

Assuming the original author hasn't upgraded to a supported OS, they should consider installing .net core or .net framework (at least 4.0) on their OS and they may have better luck.
