### ISSUE TITLE
Title in CSV

### ISSUE THREAD

**Issue by Redteamer0101** [RedSiege/EyeWitness#637]
This is the feature request.

Can we have a page title in request csv it will be easier to filter thousand of domain in category wise.

**Comment by 0x6d6f7468** [comment]
From talking with other people, it sounds like we might want to create a new CSV report in addition to the `Requests.csv`, as the existing results only seem to contain a log of requests and not the actual results.

Somewhat related to #503 

We'll take a look at this when we get a chance, because you're not alone in wanting more comprehensive CSV report output.
