### ISSUE TITLE
APT ------- /etc/apt/apt.conf.d/70proxy  $ cat /etc/apt/apt.conf.d/70proxy Acquire::http::proxy "http://localhost:3128"; Acquire::https::proxy "https://localhost:3128";  Git ----------------- $ cat ~/.gitconfig [http] proxy = http://localhost:3128  Wget --------------------- $ cat ~/.wgetrc or /etc/wgetrc  use_proxy=yes http_proxy=127.0.0.1:3128 https_proxy=127.0.0.1:3128  General system proxy --------------------------------  export HTTP_PROXY=http://localhost:3128 export HTTPS_PROXY=http://localhost:3128

### ISSUE THREAD

**Issue by larrypeterson2** [RedSiege/EyeWitness#644]

**Comment by 0x6d6f7468** [comment]
Hey @larrypeterson2, it appears that something went wrong with this issue. If there's an issue you would like to report, please edit the issue title and body, preferably using the issue template, to provide the information we need in order to begin looking into your issue.

If we don't hear back by the end of this week, we're going to close the issue due to not having enough information. Thank you in advance for your cooperation.
